# Generated by Django 3.1.1 on 2020-10-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='createBy',
            new_name='createdBy',
        ),
    ]
