# Generated by Django 3.1.1 on 2020-10-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_auto_20201008_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Via',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='new Via', max_length=100)),
                ('via_id', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField()),
                ('tfa', models.TextField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vias', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['createdDate'],
            },
        ),
    ]
