# Generated by Django 3.1.1 on 2020-10-16 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='new Workspace', max_length=100)),
                ('accessToken', models.CharField(blank=True, max_length=200)),
                ('appID', models.CharField(blank=True, max_length=100)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['createdDate'],
            },
        ),
        migrations.CreateModel(
            name='Via',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='new Via', max_length=100)),
                ('tfa', models.TextField(blank=True)),
                ('fbid', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('emailPassword', models.CharField(blank=True, max_length=100)),
                ('fbname', models.CharField(blank=True, max_length=100)),
                ('gender', models.SmallIntegerField(blank=True, null=True)),
                ('dateOfBirth', models.DateTimeField(blank=True, null=True)),
                ('linkFb', models.TextField(blank=True)),
                ('status', models.SmallIntegerField(blank=True, default=1)),
                ('label', models.TextField(blank=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vias', to='apis.workspace')),
            ],
            options={
                'ordering': ['createdDate'],
            },
        ),
        migrations.CreateModel(
            name='BM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='new Via', max_length=100)),
                ('BMID', models.CharField(blank=True, max_length=100)),
                ('balance', models.FloatField(blank=True)),
                ('status', models.SmallIntegerField(blank=True, default=1)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bms', to='apis.workspace')),
            ],
            options={
                'ordering': ['createdDate'],
            },
        ),
    ]
