# Generated by Django 3.1.2 on 2020-10-08 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['createdDate'],
            },
        ),
        migrations.CreateModel(
            name='Via',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='new Via', max_length=100)),
                ('via_id', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField()),
                ('tfa', models.TextField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vias', to='apis.workspace')),
            ],
            options={
                'ordering': ['createdDate'],
            },
        ),
    ]
