# Generated by Django 3.1.1 on 2020-10-16 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='appID',
        ),
    ]
