# Generated by Django 3.1.1 on 2020-11-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='via',
            name='status',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
