# Generated by Django 3.1.1 on 2020-10-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_workspace_appid'),
    ]

    operations = [
        migrations.AddField(
            model_name='via',
            name='accessToken',
            field=models.TextField(blank=True),
        ),
    ]
