# Generated by Django 3.1.1 on 2020-11-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20201113_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bm',
            options={},
        ),
        migrations.RenameField(
            model_name='bm',
            old_name='BmID',
            new_name='bmid',
        ),
        migrations.RemoveField(
            model_name='bm',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='bm',
            name='createdDate',
        ),
        migrations.RemoveField(
            model_name='bm',
            name='name',
        ),
    ]
