# Generated by Django 3.1.2 on 2020-10-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20201014_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='BM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='new Via', max_length=100)),
                ('BMID', models.CharField(blank=True, max_length=100)),
                ('balance', models.FloatField(blank=True)),
                ('status', models.SmallIntegerField(blank=True, default=1)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bms', to='apis.workspace')),
            ],
            options={
                'ordering': ['createdDate'],
            },
        ),
    ]
