# Generated by Django 3.1.1 on 2020-11-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20201116_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bm',
            name='status',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
