# Generated by Django 3.1.1 on 2020-10-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_via_accesstoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='via',
            old_name='fbname',
            new_name='fbName',
        ),
    ]
