# Generated by Django 3.1.1 on 2020-10-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20201016_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='via',
            old_name='linkFb',
            new_name='fbLink',
        ),
    ]
