# Generated by Django 3.1.1 on 2020-12-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('process', models.CharField(blank=True, max_length=100)),
                ('log', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('error', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
