# Generated by Django 3.1.2 on 2020-10-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20201016_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bm',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='via',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
