# Generated by Django 3.1.1 on 2020-12-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_automationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationlog',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
