# Generated by Django 3.1.1 on 2020-10-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20201021_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='via',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
