# Generated by Django 3.1.1 on 2020-10-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20201028_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.CharField(blank=True, default=1, max_length=255),
        ),
    ]
